services:
  app:
    image: karthiq18/old-app:$${SHORT_SHA}
    ports:
      - "5002:5000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    depends_on:
      - db
    restart: always

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./message.sql:/docker-entrypoint-initdb.d/message.sql
    restart: always

  db-admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA_HOST=db  # Match your MySQL service name
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
    depends_on:
      - db

volumes:

  db_data:
