name: ci cd pipeline with compose

on:
  push:
    branches:
      main

jobs:
  deploy-compose-on-ec2:
    runs-on:
      ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: build Docker image
        run: "docker build -t karthiq18/old-app:${GITHUB_SHA:0:7} ."
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push to docker hub
        run: docker push karthiq18/old-app:${GITHUB_SHA:0:7}
      - name: copying only compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST  }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Docker-compose.yaml"
          target: "/home/ubuntu/old-app"
      - name: Deploy on Ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            cd /home/ubuntu/old-app
            Docker-compose down
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/old-app:$SHORT_SHA
            Docker-compose up -d
        
      
            

